steps:

- id: "Instalando aplicação"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'app']
  env: ['GOPATH=.']

- id: "Rodando testes..."
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', './...']
  env: ['GOPATH=.']

- id: "Criando build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-hpa:latest', '.']

images:
  - 'gcr.io/$PROJECT_ID/go-hpa:latest'
